---
- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create docker image using war file
    command: docker build -t myprojectbikash:CICD .
    args:
      chdir: /opt/bikashCICD

  - name: create tag to image
    command: docker tag myprojectbikash:CICD bikash36/myprojectbikash:CICD

  - name: loginto docker
    command: docker login --username bikash36 --password Meera@1996

  - name: push image on to dockerhub
    command: docker push bikash36/myprojectbikash:CICD

  - name: remove docker images form ansible server
    command: docker rmi myprojectbikash:CICD bikash36/myprojectbikash:CICD
    ignore_errors: yes

