---
- name: Create pods using deployment
  hosts: kube
  become: true
  become_user: root

  tasks:
  - name: create a deployment
    command: kubectl apply -f https://raw.githubusercontent.com/Bikash376919/DevopsEdu/master/CICD%20pipeline/kubedeployment.yml
